### ISSUE TITLE
Package available for .NET 4.0?

### ISSUE THREAD

**Issue by christianarielli** [appccelerate/eventbroker#4]
Sorry for using the issue tracker to ask a question :( Do you have a version compiled for .NET 4.0 or ist 4.5 the minimum requirement for the EventBroker?

Regards,

Christian

**Comment by ursenzler** [comment]
Hi Christian

Nevermind.

I don't have the time to support multiple versions. But you can fork the repo, and change the target framework from 4.5 to 4. I think that should not be a problem.

Then you can either build your own package if you know how to use nuget or you can open a pull request onto the master. I'll ignore the pull request, but the nice thing is that our build server will build your version and create a nuget package (with a prerelase version) and put it on the Appccelerate feed on myget.org (https://www.myget.org/gallery/appccelerate).

The event broker is very stable (no new features, no newly found bugs), so forking gives you a quick solution until your project upgrades to a newer .net version (which you should do :-) )

Let me know if this helps.

Happy coding
Urs

**Comment by michaelestermann** [comment]
When this is still required, set the target framework to [net40](https://docs.microsoft.com/en-us/dotnet/standard/frameworks).
