### ISSUE TITLE
Possible to migrate to netstandard

### ISSUE THREAD

**Issue by mwpowellhtx** [appccelerate/eventbroker#6]
Possibly along the same lines as [4.5 versus 4](4). Any plans to migrate supporting `netstandard2`? Or, if `4.5` is a firm requirement of yours, multitarget. Thank you...

**Comment by ursenzler** [comment]
The code is already compliant to .Net standard 2.0, thanks to @michaelestermann. However, there is no official nuget release yet.

**Comment by ursenzler** [comment]
For a quick fix, build it yourself.

**Comment by michaelestermann** [comment]
Support has been added in the latest version [4.0](https://www.nuget.org/packages/Appccelerate.EventBroker/). 
Please consider the migration documentation available on nuget.org when upgrading.

Closing the issue therefor.
